language: php

php:
  - 5.5

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y --force-yes php5-cli php5-curl php5-intl

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - sleep 5

script:
  - bin/behat --stop-on-failure

